version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - APP_PORT=8080
      - GIN_MODE=release
      - CONFIG_PATH=/root

  redis:
    image: "redis:6.2-alpine"
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: